import type { Organization, Project, Inspector, Inspection, Alert, Scheme, Complaint } from '../types';

const now = new Date().toISOString();

export const demoSchemes: Scheme[] = [
  { schemeId: 'SCHEME001', schemeName: 'SC Welfare Programme', department: 'DoSJE', ministry: 'MoSJE', description: 'Welfare for Scheduled Castes', targetBeneficiaries: 'SC communities', eligibility: 'SC Certificate', status: 'ACTIVE', dataSourceType: 'DEMO', lastVerifiedAt: now },
  { schemeId: 'SCHEME002', schemeName: 'OBC Welfare Programme', department: 'DoSJE', ministry: 'MoSJE', description: 'Welfare for Other Backward Classes', targetBeneficiaries: 'OBC communities', eligibility: 'OBC Certificate', status: 'ACTIVE', dataSourceType: 'DEMO', lastVerifiedAt: now },
  { schemeId: 'SCHEME003', schemeName: 'Senior Citizen Welfare Programme', department: 'DoSJE', ministry: 'MoSJE', description: 'Care and support for elderly', targetBeneficiaries: 'Senior Citizens', eligibility: 'Age 60+', status: 'ACTIVE', dataSourceType: 'DEMO', lastVerifiedAt: now },
  { schemeId: 'SCHEME004', schemeName: 'Drug Demand Reduction Programme', department: 'DoSJE', ministry: 'MoSJE', description: 'Rehabilitation of substance abusers', targetBeneficiaries: 'Substance Abusers', eligibility: 'Identified individuals', status: 'ACTIVE', dataSourceType: 'DEMO', lastVerifiedAt: now },
  { schemeId: 'SCHEME005', schemeName: 'Social Empowerment Programme', department: 'DoSJE', ministry: 'MoSJE', description: 'General social empowerment', targetBeneficiaries: 'Marginalized', eligibility: 'Income Criteria', status: 'ACTIVE', dataSourceType: 'DEMO', lastVerifiedAt: now },
  { schemeId: 'SCHEME006', schemeName: 'Community Development Programme', department: 'DoSJE', ministry: 'MoSJE', description: 'Local community building', targetBeneficiaries: 'Rural communities', eligibility: 'Community level', status: 'ACTIVE', dataSourceType: 'DEMO', lastVerifiedAt: now },
  { schemeId: 'SCHEME007', schemeName: 'Rehabilitation Support Programme', department: 'DoSJE', ministry: 'MoSJE', description: 'Rehab for destitute', targetBeneficiaries: 'Destitute', eligibility: 'Identified destitute', status: 'ACTIVE', dataSourceType: 'DEMO', lastVerifiedAt: now },
  { schemeId: 'SCHEME008', schemeName: 'Sanitation Worker Welfare Programme', department: 'DoSJE', ministry: 'MoSJE', description: 'Welfare of sanitation workers', targetBeneficiaries: 'Sanitation Workers', eligibility: 'Occupational proof', status: 'ACTIVE', dataSourceType: 'DEMO', lastVerifiedAt: now },
  { schemeId: 'SCHEME009', schemeName: 'Scholarship Support Programme', department: 'DoSJE', ministry: 'MoSJE', description: 'Educational scholarships', targetBeneficiaries: 'Students', eligibility: 'Merit and Income', status: 'ACTIVE', dataSourceType: 'DEMO', lastVerifiedAt: now },
  { schemeId: 'SCHEME010', schemeName: 'Skill Development Programme', department: 'DoSJE', ministry: 'MoSJE', description: 'Vocational training', targetBeneficiaries: 'Youth', eligibility: 'Age 18-35', status: 'ACTIVE', dataSourceType: 'DEMO', lastVerifiedAt: now }
];

export const demoOrganizations: Organization[] = [
  // GOVERNMENT INSTITUTIONS
  { id: 'GOV001', organizationName: 'National Institute of Social Defence', organizationType: 'GOVERNMENT_INSTITUTION', state: 'Delhi', district: 'New Delhi', schemeIds: ['SCHEME001'], projectIds: [], address: 'New Delhi', pincode: '110001', latitude: 28.6139, longitude: 77.2090, phone: '011-20000001', email: 'director@nisd.gov.in', status: 'ACTIVE', riskLevel: 'LOW', riskScore: 24, dataSourceType: 'DEMO', lastVerifiedAt: now, previousViolations: 0, inspectionDelayDays: 0, complaintsCount: 0, cctvAnomalies: 0, financialIrregularityFlags: 0, complianceScore: 76 },
  { id: 'GOV002', organizationName: 'National Scheduled Castes Finance and Development Corporation', organizationType: 'CORPORATION', state: 'Delhi', district: 'New Delhi', schemeIds: ['SCHEME001'], projectIds: [], address: 'New Delhi', pincode: '110001', latitude: 28.6200, longitude: 77.2100, phone: '011-20000002', email: 'info@nsfdc.nic.in', status: 'ACTIVE', riskLevel: 'MEDIUM', riskScore: 47, dataSourceType: 'DEMO', lastVerifiedAt: now, previousViolations: 1, inspectionDelayDays: 5, complaintsCount: 1, cctvAnomalies: 0, financialIrregularityFlags: 0, complianceScore: 53 },
  { id: 'GOV003', organizationName: 'National Backward Classes Finance and Development Corporation', organizationType: 'CORPORATION', state: 'Delhi', district: 'New Delhi', schemeIds: ['SCHEME002'], projectIds: [], address: 'New Delhi', pincode: '110001', latitude: 28.6150, longitude: 77.2050, phone: '011-20000003', email: 'nbcfdc@nic.in', status: 'ACTIVE', riskLevel: 'LOW', riskScore: 28, dataSourceType: 'DEMO', lastVerifiedAt: now, previousViolations: 0, inspectionDelayDays: 2, complaintsCount: 0, cctvAnomalies: 0, financialIrregularityFlags: 0, complianceScore: 72 },
  { id: 'GOV004', organizationName: 'National Safai Karamcharis Finance and Development Corporation', organizationType: 'CORPORATION', state: 'Delhi', district: 'New Delhi', schemeIds: ['SCHEME008'], projectIds: [], address: 'New Delhi', pincode: '110001', latitude: 28.6250, longitude: 77.2150, phone: '011-20000004', email: 'nskfdc@nic.in', status: 'ACTIVE', riskLevel: 'HIGH', riskScore: 67, dataSourceType: 'DEMO', lastVerifiedAt: now, previousViolations: 3, inspectionDelayDays: 15, complaintsCount: 2, cctvAnomalies: 1, financialIrregularityFlags: 0, complianceScore: 33 },
  { id: 'GOV005', organizationName: 'Dr. Ambedkar Foundation', organizationType: 'FOUNDATION', state: 'Delhi', district: 'New Delhi', schemeIds: ['SCHEME005'], projectIds: [], address: 'New Delhi', pincode: '110001', latitude: 28.6300, longitude: 77.2200, phone: '011-20000005', email: 'daf-social@nic.in', status: 'ACTIVE', riskLevel: 'LOW', riskScore: 21, dataSourceType: 'DEMO', lastVerifiedAt: now, previousViolations: 0, inspectionDelayDays: 0, complaintsCount: 0, cctvAnomalies: 0, financialIrregularityFlags: 0, complianceScore: 79 },
  { id: 'GOV006', organizationName: 'Babu Jagjivan Ram National Foundation', organizationType: 'FOUNDATION', state: 'Delhi', district: 'New Delhi', schemeIds: ['SCHEME005'], projectIds: [], address: 'New Delhi', pincode: '110001', latitude: 28.6350, longitude: 77.2250, phone: '011-20000006', email: 'bjrnf@nic.in', status: 'ACTIVE', riskLevel: 'LOW', riskScore: 26, dataSourceType: 'DEMO', lastVerifiedAt: now, previousViolations: 0, inspectionDelayDays: 1, complaintsCount: 0, cctvAnomalies: 0, financialIrregularityFlags: 0, complianceScore: 74 },
  { id: 'GOV007', organizationName: 'Development and Welfare Board for DNT/NT/SNT', organizationType: 'BOARD', state: 'Delhi', district: 'New Delhi', schemeIds: ['SCHEME006'], projectIds: [], address: 'New Delhi', pincode: '110001', latitude: 28.6400, longitude: 77.2300, phone: '011-20000007', email: 'dntboard@nic.in', status: 'ACTIVE', riskLevel: 'MEDIUM', riskScore: 52, dataSourceType: 'DEMO', lastVerifiedAt: now, previousViolations: 2, inspectionDelayDays: 8, complaintsCount: 1, cctvAnomalies: 0, financialIrregularityFlags: 0, complianceScore: 48 },
  { id: 'GOV008', organizationName: 'National Commission for Scheduled Castes', organizationType: 'COMMISSION', state: 'Delhi', district: 'New Delhi', schemeIds: ['SCHEME001'], projectIds: [], address: 'New Delhi', pincode: '110001', latitude: 28.6450, longitude: 77.2350, phone: '011-20000008', email: 'ncsc-hq@nic.in', status: 'ACTIVE', riskLevel: 'LOW', riskScore: 19, dataSourceType: 'DEMO', lastVerifiedAt: now, previousViolations: 0, inspectionDelayDays: 0, complaintsCount: 0, cctvAnomalies: 0, financialIrregularityFlags: 0, complianceScore: 81 },
  { id: 'GOV009', organizationName: 'National Commission for Backward Classes', organizationType: 'COMMISSION', state: 'Delhi', district: 'New Delhi', schemeIds: ['SCHEME002'], projectIds: [], address: 'New Delhi', pincode: '110001', latitude: 28.6500, longitude: 77.2400, phone: '011-20000009', email: 'ncbc-hq@nic.in', status: 'ACTIVE', riskLevel: 'LOW', riskScore: 22, dataSourceType: 'DEMO', lastVerifiedAt: now, previousViolations: 0, inspectionDelayDays: 0, complaintsCount: 0, cctvAnomalies: 0, financialIrregularityFlags: 0, complianceScore: 78 },
  { id: 'GOV010', organizationName: 'National Commission for Safai Karamcharis', organizationType: 'COMMISSION', state: 'Delhi', district: 'New Delhi', schemeIds: ['SCHEME008'], projectIds: [], address: 'New Delhi', pincode: '110001', latitude: 28.6550, longitude: 77.2450, phone: '011-20000010', email: 'ncsk-hq@nic.in', status: 'ACTIVE', riskLevel: 'MEDIUM', riskScore: 44, dataSourceType: 'DEMO', lastVerifiedAt: now, previousViolations: 1, inspectionDelayDays: 6, complaintsCount: 0, cctvAnomalies: 0, financialIrregularityFlags: 0, complianceScore: 56 },

  // REAL NGOs (Representational Data)
  { id: 'NGO001', organizationName: 'Akshaya Patra Foundation', organizationType: 'NGO', state: 'Karnataka', district: 'Bengaluru', schemeIds: ['SCHEME009'], projectIds: [], address: 'Bengaluru', pincode: '560010', latitude: 13.0068, longitude: 77.5511, phone: '18004258622', email: 'infodesk@akshayapatra.org', status: 'ACTIVE', riskLevel: 'LOW', riskScore: 12, dataSourceType: 'DEMO', lastVerifiedAt: now, previousViolations: 0, inspectionDelayDays: 0, complaintsCount: 0, cctvAnomalies: 0, financialIrregularityFlags: 0, complianceScore: 92 },
  { id: 'NGO002', organizationName: 'Smile Foundation', organizationType: 'NGO', state: 'Delhi', district: 'New Delhi', schemeIds: ['SCHEME006'], projectIds: [], address: 'Okhla Industrial Estate', pincode: '110020', latitude: 28.5355, longitude: 77.2639, phone: '011-41354565', email: 'info@smilefoundationindia.org', status: 'ACTIVE', riskLevel: 'LOW', riskScore: 18, dataSourceType: 'DEMO', lastVerifiedAt: now, previousViolations: 0, inspectionDelayDays: 1, complaintsCount: 0, cctvAnomalies: 0, financialIrregularityFlags: 0, complianceScore: 88 },
  { id: 'NGO003', organizationName: 'Goonj', organizationType: 'NGO', state: 'Delhi', district: 'New Delhi', schemeIds: ['SCHEME005'], projectIds: [], address: 'Sarita Vihar', pincode: '110076', latitude: 28.5303, longitude: 77.2889, phone: '011-26972351', email: 'mail@goonj.org', status: 'ACTIVE', riskLevel: 'LOW', riskScore: 15, dataSourceType: 'DEMO', lastVerifiedAt: now, previousViolations: 0, inspectionDelayDays: 0, complaintsCount: 0, cctvAnomalies: 0, financialIrregularityFlags: 0, complianceScore: 90 },
  { id: 'NGO004', organizationName: 'HelpAge India', organizationType: 'NGO', state: 'Delhi', district: 'New Delhi', schemeIds: ['SCHEME003'], projectIds: [], address: 'Qutab Institutional Area', pincode: '110016', latitude: 28.5413, longitude: 77.1824, phone: '18001801253', email: 'headoffice@helpageindia.org', status: 'ACTIVE', riskLevel: 'LOW', riskScore: 22, dataSourceType: 'DEMO', lastVerifiedAt: now, previousViolations: 0, inspectionDelayDays: 2, complaintsCount: 0, cctvAnomalies: 0, financialIrregularityFlags: 0, complianceScore: 85 },
  { id: 'NGO005', organizationName: 'Pratham Education Foundation', organizationType: 'NGO', state: 'Maharashtra', district: 'Mumbai', schemeIds: ['SCHEME009'], projectIds: [], address: 'Safdarjung Enclave', pincode: '400028', latitude: 19.0195, longitude: 72.8436, phone: '022-24376326', email: 'info@pratham.org', status: 'ACTIVE', riskLevel: 'MEDIUM', riskScore: 45, dataSourceType: 'DEMO', lastVerifiedAt: now, previousViolations: 1, inspectionDelayDays: 4, complaintsCount: 1, cctvAnomalies: 0, financialIrregularityFlags: 0, complianceScore: 65 },
  { id: 'NGO006', organizationName: 'Save the Children India', organizationType: 'NGO', state: 'Haryana', district: 'Gurugram', schemeIds: ['SCHEME009'], projectIds: [], address: 'Sector 44', pincode: '122003', latitude: 28.4503, longitude: 77.0620, phone: '0124-4752000', email: 'info@savethechildren.in', status: 'ACTIVE', riskLevel: 'LOW', riskScore: 20, dataSourceType: 'DEMO', lastVerifiedAt: now, previousViolations: 0, inspectionDelayDays: 0, complaintsCount: 0, cctvAnomalies: 0, financialIrregularityFlags: 0, complianceScore: 86 },
  { id: 'NGO007', organizationName: 'Kailash Satyarthi Children\'s Foundation', organizationType: 'NGO', state: 'Delhi', district: 'New Delhi', schemeIds: ['SCHEME005'], projectIds: [], address: 'Okhla Phase-III', pincode: '110020', latitude: 28.5452, longitude: 77.2711, phone: '011-49211111', email: 'info@satyarthi.org', status: 'ACTIVE', riskLevel: 'LOW', riskScore: 14, dataSourceType: 'DEMO', lastVerifiedAt: now, previousViolations: 0, inspectionDelayDays: 0, complaintsCount: 0, cctvAnomalies: 0, financialIrregularityFlags: 0, complianceScore: 91 },
  { id: 'NGO008', organizationName: 'Oxfam India', organizationType: 'NGO', state: 'Delhi', district: 'New Delhi', schemeIds: ['SCHEME005'], projectIds: [], address: 'Okhla Industrial Estate', pincode: '110020', latitude: 28.5355, longitude: 77.2639, phone: '011-46538000', email: 'delhi@oxfamindia.org', status: 'ACTIVE', riskLevel: 'HIGH', riskScore: 68, dataSourceType: 'DEMO', lastVerifiedAt: now, previousViolations: 2, inspectionDelayDays: 12, complaintsCount: 3, cctvAnomalies: 1, financialIrregularityFlags: 0, complianceScore: 35 },
  { id: 'NGO009', organizationName: 'Snehalaya', organizationType: 'NGO', state: 'Maharashtra', district: 'Ahmednagar', schemeIds: ['SCHEME004'], projectIds: [], address: 'MIDC', pincode: '414111', latitude: 19.1417, longitude: 74.7431, phone: '0241-2778353', email: 'info@snehalaya.org', status: 'ACTIVE', riskLevel: 'MEDIUM', riskScore: 35, dataSourceType: 'DEMO', lastVerifiedAt: now, previousViolations: 1, inspectionDelayDays: 5, complaintsCount: 0, cctvAnomalies: 0, financialIrregularityFlags: 0, complianceScore: 70 },
  { id: 'NGO010', organizationName: 'Navjyoti India Foundation', organizationType: 'NGO', state: 'Haryana', district: 'Gurugram', schemeIds: ['SCHEME006'], projectIds: [], address: 'Sector 55', pincode: '122011', latitude: 28.4116, longitude: 77.1009, phone: '0124-4061614', email: 'navjyoti@navjyoti.org.in', status: 'ACTIVE', riskLevel: 'HIGH', riskScore: 76, dataSourceType: 'DEMO', lastVerifiedAt: now, previousViolations: 4, inspectionDelayDays: 22, complaintsCount: 3, cctvAnomalies: 2, financialIrregularityFlags: 1, complianceScore: 24 }
];

export const demoProjects: Project[] = [
  { 
    projectId: 'PRJ001', 
    projectName: 'Nasha Mukt Bharat Abhiyaan (NMBA) - Substance Demand Reduction & IRCA Modernization', 
    organizationId: 'GOV001', 
    schemeId: 'SCHEME004', 
    projectType: 'REHABILITATION', 
    description: 'Flagship national campaign establishing integrated counseling, de-addiction recovery, and hospital outreach across high-risk districts in India.', 
    targetBeneficiaries: 15000, 
    actualBeneficiaries: 12850, 
    budget: 85000000, 
    grantAmount: 75000000, 
    startDate: '2022-08-15', 
    endDate: '2026-03-31', 
    state: 'Delhi', 
    district: 'New Delhi', 
    projectStatus: 'ACTIVE', 
    riskScore: 12, 
    dataSourceType: 'DEMO' 
  },
  { 
    projectId: 'PRJ002', 
    projectName: 'HelpAge India Mobile Medical Units (MMU) & Elder-Line 14567 Geriatric Healthcare', 
    organizationId: 'NGO004', 
    schemeId: 'SCHEME003', 
    projectType: 'SERVICES', 
    description: 'Providing doorstep primary medical diagnosis, chronic disease medicines, and cataract screenings for rural destitute senior citizens across underserved blocks.', 
    targetBeneficiaries: 45000, 
    actualBeneficiaries: 42300, 
    budget: 32000000, 
    grantAmount: 28000000, 
    startDate: '2023-04-01', 
    endDate: '2025-03-31', 
    state: 'Delhi', 
    district: 'New Delhi', 
    projectStatus: 'ACTIVE', 
    riskScore: 6, 
    dataSourceType: 'DEMO' 
  },
  { 
    projectId: 'PRJ003', 
    projectName: 'Navjeevan Integrated Rehabilitation Centre for Addicts (IRCA) - Youth Detox & Recovery Pilot', 
    organizationId: 'NGO003', 
    schemeId: 'SCHEME004', 
    projectType: 'REHABILITATION', 
    description: 'Inpatient rehabilitation centre providing psychological therapy, vocational retraining, and medical de-addiction under NAPDDR framework.', 
    targetBeneficiaries: 600, 
    actualBeneficiaries: 240, 
    budget: 12000000, 
    grantAmount: 9500000, 
    startDate: '2022-06-01', 
    endDate: '2025-05-31', 
    state: 'Telangana', 
    district: 'Hyderabad', 
    projectStatus: 'UNDER_REVIEW', 
    riskScore: 88, 
    dataSourceType: 'DEMO' 
  },
  { 
    projectId: 'PRJ004', 
    projectName: 'PM-DAKSH National Skill Upskilling & Apparel Manufacturing Training for SC Youth', 
    organizationId: 'GOV002', 
    schemeId: 'SCHEME001', 
    projectType: 'TRAINING', 
    description: 'Pradhan Mantri Dakshta Aur Kushalta Sampann Hitgrahi scheme providing NSQF aligned skill training, toolkits, and wage employment for SC beneficiaries.', 
    targetBeneficiaries: 5000, 
    actualBeneficiaries: 4650, 
    budget: 45000000, 
    grantAmount: 45000000, 
    startDate: '2023-01-10', 
    endDate: '2026-01-09', 
    state: 'Delhi', 
    district: 'New Delhi', 
    projectStatus: 'ACTIVE', 
    riskScore: 18, 
    dataSourceType: 'DEMO' 
  },
  { 
    projectId: 'PRJ005', 
    projectName: 'NBCFDC Concessional Micro-Finance & Livelihood Scheme for Traditional OBC Artisans', 
    organizationId: 'GOV003', 
    schemeId: 'SCHEME002', 
    projectType: 'FINANCIAL_SUPPORT', 
    description: 'Low-interest concessional credit and technology upgrade grants for weavers, potters, blacksmiths, and handicraft artisans belonging to backward classes.', 
    targetBeneficiaries: 12000, 
    actualBeneficiaries: 10400, 
    budget: 120000000, 
    grantAmount: 120000000, 
    startDate: '2022-04-01', 
    endDate: '2026-03-31', 
    state: 'Delhi', 
    district: 'New Delhi', 
    projectStatus: 'ACTIVE', 
    riskScore: 14, 
    dataSourceType: 'DEMO' 
  },
  { 
    projectId: 'PRJ006', 
    projectName: 'NAMASTE - Sewer & Septic Tank Sanitation Workers Safety Profiling & PPE Provisioning', 
    organizationId: 'GOV004', 
    schemeId: 'SCHEME008', 
    projectType: 'SERVICES', 
    description: 'National Action for Mechanised Sanitation Ecosystem: eliminating hazardous manual sewer entries by distributing robotic cleaning kits and safety harnesses.', 
    targetBeneficiaries: 25000, 
    actualBeneficiaries: 21500, 
    budget: 95000000, 
    grantAmount: 90000000, 
    startDate: '2023-05-01', 
    endDate: '2026-04-30', 
    state: 'Delhi', 
    district: 'New Delhi', 
    projectStatus: 'ACTIVE', 
    riskScore: 54, 
    dataSourceType: 'DEMO' 
  },
  { 
    projectId: 'PRJ007', 
    projectName: 'Disaster Rehabilitation & Livelihood Restoration for Flood Affected Marginalized Communities', 
    organizationId: 'NGO008', 
    schemeId: 'SCHEME007', 
    projectType: 'REHABILITATION', 
    description: 'Emergency shelter reconstruction, community water filters, and micro-grant distribution for vulnerable scheduled caste families in flood prone zones.', 
    targetBeneficiaries: 2000, 
    actualBeneficiaries: 850, 
    budget: 18000000, 
    grantAmount: 14000000, 
    startDate: '2023-08-01', 
    endDate: '2025-07-31', 
    state: 'Odisha', 
    district: 'Cuttack', 
    projectStatus: 'SUSPENDED', 
    riskScore: 89, 
    dataSourceType: 'DEMO' 
  },
  { 
    projectId: 'PRJ008', 
    projectName: 'Pratham "Read India" - Foundational Literacy & Numeracy (FLN) Mission', 
    organizationId: 'NGO005', 
    schemeId: 'SCHEME010', 
    projectType: 'TRAINING', 
    description: 'Accelerated pedagogical learning camps improving reading and math competence for 1st to 5th grade students across rural Maharashtra government schools.', 
    targetBeneficiaries: 30000, 
    actualBeneficiaries: 28400, 
    budget: 25000000, 
    grantAmount: 22000000, 
    startDate: '2023-06-01', 
    endDate: '2025-05-31', 
    state: 'Maharashtra', 
    district: 'Pune', 
    projectStatus: 'ACTIVE', 
    riskScore: 22, 
    dataSourceType: 'DEMO' 
  },
  { 
    projectId: 'PRJ009', 
    projectName: 'Snehalaya Snehankur - 24x7 Shelter & Medical Transit Care for Destitute Women & Infants', 
    organizationId: 'NGO009', 
    schemeId: 'SCHEME005', 
    projectType: 'REHABILITATION', 
    description: 'Healthcare shelter providing nutrition, pediatric medical supervision, legal counsel, and vocational independence for rescued women and infants.', 
    targetBeneficiaries: 1200, 
    actualBeneficiaries: 1150, 
    budget: 14000000, 
    grantAmount: 14000000, 
    startDate: '2023-01-01', 
    endDate: '2025-12-31', 
    state: 'Maharashtra', 
    district: 'Ahmednagar', 
    projectStatus: 'ACTIVE', 
    riskScore: 16, 
    dataSourceType: 'DEMO' 
  },
  { 
    projectId: 'PRJ010', 
    projectName: 'Dr. Ambedkar National Merit Scholarship & Research Fellowship Disbursement Portal', 
    organizationId: 'GOV005', 
    schemeId: 'SCHEME005', 
    projectType: 'SERVICES', 
    description: 'End-to-end direct benefit transfer (DBT) disbursal of merit awards and PhD research fellowships for deserving students from SC/ST communities.', 
    targetBeneficiaries: 8000, 
    actualBeneficiaries: 7850, 
    budget: 65000000, 
    grantAmount: 65000000, 
    startDate: '2022-07-01', 
    endDate: '2027-06-30', 
    state: 'Delhi', 
    district: 'New Delhi', 
    projectStatus: 'ACTIVE', 
    riskScore: 8, 
    dataSourceType: 'DEMO' 
  },
  { 
    projectId: 'PRJ011', 
    projectName: 'Smile on Wheels - High-Tech Mobile Hospital Healthcare Units for Slum Clusters', 
    organizationId: 'NGO002', 
    schemeId: 'SCHEME006', 
    projectType: 'SERVICES', 
    description: 'Fully-equipped medical diagnosis vans offering point-of-care pathology, ECG, maternity checkups, and free medicines across Delhi-NCR industrial colonies.', 
    targetBeneficiaries: 35000, 
    actualBeneficiaries: 33200, 
    budget: 28000000, 
    grantAmount: 25000000, 
    startDate: '2023-03-01', 
    endDate: '2025-02-28', 
    state: 'Delhi', 
    district: 'New Delhi', 
    projectStatus: 'ACTIVE', 
    riskScore: 11, 
    dataSourceType: 'DEMO' 
  },
  { 
    projectId: 'PRJ012', 
    projectName: 'Mukti Ashram Transit Rehabilitation & Protection Home for Rescued Child Labourers', 
    organizationId: 'NGO007', 
    schemeId: 'SCHEME005', 
    projectType: 'REHABILITATION', 
    description: 'Comprehensive interim care home providing emergency medical treatment, trauma de-escalation, and non-formal bridge education for rescued bonded child workers.', 
    targetBeneficiaries: 1500, 
    actualBeneficiaries: 1480, 
    budget: 19000000, 
    grantAmount: 19000000, 
    startDate: '2023-01-15', 
    endDate: '2026-01-14', 
    state: 'Delhi', 
    district: 'New Delhi', 
    projectStatus: 'ACTIVE', 
    riskScore: 7, 
    dataSourceType: 'DEMO' 
  },
  { 
    projectId: 'PRJ013', 
    projectName: 'NISD National Certificate Programme in Geriatric Care & Dementia Support Outreach', 
    organizationId: 'GOV001', 
    schemeId: 'SCHEME007', 
    projectType: 'TRAINING', 
    description: 'Professional skilling of certified geriatric healthcare attendants to cater to the care needs of bedridden and Alzheimer elderly citizens.', 
    targetBeneficiaries: 3000, 
    actualBeneficiaries: 2900, 
    budget: 22000000, 
    grantAmount: 22000000, 
    startDate: '2023-04-01', 
    endDate: '2026-03-31', 
    state: 'Delhi', 
    district: 'New Delhi', 
    projectStatus: 'ACTIVE', 
    riskScore: 15, 
    dataSourceType: 'DEMO' 
  },
  { 
    projectId: 'PRJ014', 
    projectName: 'Babu Jagjivan Ram National Youth Leadership & Constitutional Equality Academy', 
    organizationId: 'GOV006', 
    schemeId: 'SCHEME005', 
    projectType: 'TRAINING', 
    description: 'Residential leadership bootcamps on social justice, human rights, and public administration for marginalized university scholars.', 
    targetBeneficiaries: 1200, 
    actualBeneficiaries: 1180, 
    budget: 16000000, 
    grantAmount: 16000000, 
    startDate: '2023-05-15', 
    endDate: '2025-05-14', 
    state: 'Delhi', 
    district: 'New Delhi', 
    projectStatus: 'ACTIVE', 
    riskScore: 10, 
    dataSourceType: 'DEMO' 
  },
  { 
    projectId: 'PRJ015', 
    projectName: 'Akshaya Patra PM-POSHAN Mega Automated Kitchen - Daily Nutrition for 2.2 Lakh Children', 
    organizationId: 'NGO001', 
    schemeId: 'SCHEME009', 
    projectType: 'SERVICES', 
    description: 'ISO-certified centralized stainless-steel steam kitchen cooking and delivering hot, fortified mid-day meals to 1,400+ government schools in Bengaluru.', 
    targetBeneficiaries: 220000, 
    actualBeneficiaries: 218500, 
    budget: 180000000, 
    grantAmount: 160000000, 
    startDate: '2022-04-01', 
    endDate: '2027-03-31', 
    state: 'Karnataka', 
    district: 'Bengaluru', 
    projectStatus: 'ACTIVE', 
    riskScore: 4, 
    dataSourceType: 'DEMO' 
  },
  { 
    projectId: 'PRJ016', 
    projectName: 'Save the Children Inclusive Learning & Child Protection Centres in Urban Slums', 
    organizationId: 'NGO006', 
    schemeId: 'SCHEME006', 
    projectType: 'AWARENESS', 
    description: 'Setting up child friendly spaces, WASH facilities, and remedial bridge classes for children of migrant construction workers in Gurugram.', 
    targetBeneficiaries: 8000, 
    actualBeneficiaries: 7600, 
    budget: 21000000, 
    grantAmount: 20000000, 
    startDate: '2023-07-01', 
    endDate: '2025-06-30', 
    state: 'Haryana', 
    district: 'Gurugram', 
    projectStatus: 'ACTIVE', 
    riskScore: 13, 
    dataSourceType: 'DEMO' 
  },
  { 
    projectId: 'PRJ017', 
    projectName: 'Navjyoti Community Skill Development & Crime Prevention Youth Training Initiative', 
    organizationId: 'NGO010', 
    schemeId: 'SCHEME009', 
    projectType: 'SERVICES', 
    description: 'Vocational computer education, retail sales training, and community policing awareness to divert vulnerable adolescents from delinquency.', 
    targetBeneficiaries: 2500, 
    actualBeneficiaries: 1100, 
    budget: 15000000, 
    grantAmount: 11000000, 
    startDate: '2023-02-01', 
    endDate: '2025-01-31', 
    state: 'Haryana', 
    district: 'Gurugram', 
    projectStatus: 'UNDER_REVIEW', 
    riskScore: 78, 
    dataSourceType: 'DEMO' 
  },
  { 
    projectId: 'PRJ018', 
    projectName: 'SEED (Scheme for Economic Empowerment of DNTs) - Health Insurance & Skill Training', 
    organizationId: 'GOV007', 
    schemeId: 'SCHEME006', 
    projectType: 'SERVICES', 
    description: 'Facilitating PMJAY health insurance cards, community coaching for competitive exams, and livelihood support for Nomadic & Semi-Nomadic communities.', 
    targetBeneficiaries: 10000, 
    actualBeneficiaries: 8900, 
    budget: 42000000, 
    grantAmount: 42000000, 
    startDate: '2023-03-01', 
    endDate: '2026-02-28', 
    state: 'Delhi', 
    district: 'New Delhi', 
    projectStatus: 'ACTIVE', 
    riskScore: 26, 
    dataSourceType: 'DEMO' 
  },
  { 
    projectId: 'PRJ019', 
    projectName: 'NCSC National Scheduled Castes Atrocity Relief & Compensation Tracking Pipeline', 
    organizationId: 'GOV008', 
    schemeId: 'SCHEME001', 
    projectType: 'SERVICES', 
    description: 'Statutory monitoring of timely relief and rehabilitation assistance under the PoA Act across state district magistrate administrations.', 
    targetBeneficiaries: 18000, 
    actualBeneficiaries: 16200, 
    budget: 35000000, 
    grantAmount: 35000000, 
    startDate: '2023-09-01', 
    endDate: '2026-08-31', 
    state: 'Delhi', 
    district: 'New Delhi', 
    projectStatus: 'ACTIVE', 
    riskScore: 17, 
    dataSourceType: 'DEMO' 
  },
  { 
    projectId: 'PRJ020', 
    projectName: 'Goonj "Cloth for Work" (Chahak) - Community-Led Rural Water Bodies & Road Revival', 
    organizationId: 'NGO003', 
    schemeId: 'SCHEME006', 
    projectType: 'INFRASTRUCTURE', 
    description: 'Empowering village communities to repair check-dams, dig irrigation ponds, and build bamboo bridges, rewarded with comprehensive family dignity kits.', 
    targetBeneficiaries: 40000, 
    actualBeneficiaries: 38500, 
    budget: 48000000, 
    grantAmount: 45000000, 
    startDate: '2022-10-01', 
    endDate: '2026-09-30', 
    state: 'Delhi', 
    district: 'New Delhi', 
    projectStatus: 'ACTIVE', 
    riskScore: 9, 
    dataSourceType: 'DEMO' 
  }
];

export const demoInspectors: Inspector[] = [
  { inspectorId: 'INS001', name: 'Arun Kumar', employeeCode: 'EMP-001', designation: 'Senior Inspector', specialization: ['INFRASTRUCTURE'], availabilityStatus: 'AVAILABLE', department: 'DoSJE', state: 'Delhi', district: 'New Delhi', assignedInspectionCount: 2, dataSourceType: 'DEMO' },
  { inspectorId: 'INS002', name: 'Priya Sharma', employeeCode: 'EMP-002', designation: 'Field Officer', specialization: ['SERVICES'], availabilityStatus: 'AVAILABLE', department: 'State Govt', state: 'Karnataka', district: 'Bengaluru Urban', assignedInspectionCount: 1, dataSourceType: 'DEMO' },
  { inspectorId: 'INS003', name: 'Rahul Desai', employeeCode: 'EMP-003', designation: 'Auditor', specialization: ['FINANCIAL_SUPPORT'], availabilityStatus: 'ASSIGNED', department: 'Independent Auditor', state: 'Maharashtra', district: 'Pune', assignedInspectionCount: 0, dataSourceType: 'DEMO' },
  { inspectorId: 'INS004', name: 'Anita Reddy', employeeCode: 'EMP-004', designation: 'Lead Inspector', specialization: ['REHABILITATION'], availabilityStatus: 'AVAILABLE', department: 'DoSJE', state: 'Telangana', district: 'Hyderabad', assignedInspectionCount: 0, dataSourceType: 'DEMO' },
  { inspectorId: 'INS005', name: 'Vikram Singh', employeeCode: 'EMP-005', designation: 'Field Officer', specialization: ['TRAINING'], availabilityStatus: 'ON_INSPECTION', department: 'State Govt', state: 'Uttar Pradesh', district: 'Lucknow', assignedInspectionCount: 4, dataSourceType: 'DEMO' },
  { inspectorId: 'INS006', name: 'Meera Iyer', employeeCode: 'EMP-006', designation: 'Auditor', specialization: ['AWARENESS'], availabilityStatus: 'AVAILABLE', department: 'Independent Auditor', state: 'Tamil Nadu', district: 'Chennai', assignedInspectionCount: 2, dataSourceType: 'DEMO' },
  { inspectorId: 'INS007', name: 'Sanjay Patel', employeeCode: 'EMP-007', designation: 'Senior Inspector', specialization: ['SERVICES'], availabilityStatus: 'AVAILABLE', department: 'DoSJE', state: 'Gujarat', district: 'Ahmedabad', assignedInspectionCount: 1, dataSourceType: 'DEMO' },
  { inspectorId: 'INS008', name: 'Kavita Das', employeeCode: 'EMP-008', designation: 'Field Officer', specialization: ['INFRASTRUCTURE'], availabilityStatus: 'UNAVAILABLE', department: 'State Govt', state: 'West Bengal', district: 'Kolkata', assignedInspectionCount: 3, dataSourceType: 'DEMO' },
  { inspectorId: 'INS009', name: 'Ravi Verma', employeeCode: 'EMP-009', designation: 'Lead Inspector', specialization: ['FINANCIAL_SUPPORT'], availabilityStatus: 'AVAILABLE', department: 'DoSJE', state: 'Rajasthan', district: 'Jaipur', assignedInspectionCount: 0, dataSourceType: 'DEMO' },
  { inspectorId: 'INS010', name: 'Sunita Mishra', employeeCode: 'EMP-010', designation: 'Auditor', specialization: ['REHABILITATION'], availabilityStatus: 'AVAILABLE', department: 'Independent Auditor', state: 'Madhya Pradesh', district: 'Bhopal', assignedInspectionCount: 2, dataSourceType: 'DEMO' },
  { inspectorId: 'INS011', name: 'Rajesh Nair', employeeCode: 'EMP-011', designation: 'Field Officer', specialization: ['TRAINING'], availabilityStatus: 'AVAILABLE', department: 'State Govt', state: 'Kerala', district: 'Thiruvananthapuram', assignedInspectionCount: 1, dataSourceType: 'DEMO' },
  { inspectorId: 'INS012', name: 'Pooja Agarwal', employeeCode: 'EMP-012', designation: 'Senior Inspector', specialization: ['AWARENESS'], availabilityStatus: 'AVAILABLE', department: 'DoSJE', state: 'Haryana', district: 'Gurugram', assignedInspectionCount: 0, dataSourceType: 'DEMO' },
  { inspectorId: 'INS013', name: 'Anil Gupta', employeeCode: 'EMP-013', designation: 'Field Officer', specialization: ['SERVICES'], availabilityStatus: 'ON_INSPECTION', department: 'State Govt', state: 'Punjab', district: 'Chandigarh', assignedInspectionCount: 2, dataSourceType: 'DEMO' },
  { inspectorId: 'INS014', name: 'Neha Joshi', employeeCode: 'EMP-014', designation: 'Auditor', specialization: ['INFRASTRUCTURE'], availabilityStatus: 'AVAILABLE', department: 'Independent Auditor', state: 'Uttarakhand', district: 'Dehradun', assignedInspectionCount: 1, dataSourceType: 'DEMO' },
  { inspectorId: 'INS015', name: 'Naveen Kumar', employeeCode: 'EMP-015', designation: 'Senior Inspector', specialization: ['FINANCIAL_SUPPORT'], availabilityStatus: 'AVAILABLE', department: 'DoSJE', state: 'Bihar', district: 'Patna', assignedInspectionCount: 3, dataSourceType: 'DEMO' }
];

import { defaultInspections } from '../data/defaultInspections';

export const demoInspections: Inspection[] = defaultInspections;

export const demoAlerts: Alert[] = [
  { id: 'ALT-1', type: 'CCTV_OFFLINE', severity: 'CRITICAL', message: 'Navjeevan Rehabilitation Society (NGO003): Main Entrance Camera OFFLINE for 6+ hours.', organizationId: 'NGO003', timestamp: now, isRead: false, dataSourceType: 'DEMO' },
  { id: 'ALT-2', type: 'RISK_ESCALATION', severity: 'HIGH', message: 'Nayi Disha Social Service Society risk score increased to 76 (HIGH) due to multiple complaints.', organizationId: 'NGO010', timestamp: now, isRead: false, dataSourceType: 'DEMO' },
  { id: 'ALT-3', type: 'INSPECTION_DELAY', severity: 'MEDIUM', message: 'Routine inspection overdue by 15 days at National Safai Karamcharis Finance.', organizationId: 'GOV004', timestamp: now, isRead: false, dataSourceType: 'DEMO' },
  { id: 'ALT-4', type: 'BENEFICIARY_DISCREPANCY', severity: 'HIGH', message: 'Discrepancy detected in beneficiary Aadhaar logs during Oxfam India field audit.', organizationId: 'NGO008', timestamp: now, isRead: false, dataSourceType: 'DEMO' },
  { id: 'ALT-5', type: 'CORRECTIVE_ACTION_OVERDUE', severity: 'MEDIUM', message: 'Corrective Action CA-003 overdue: structural repair at NSKFDC Eastern Wing.', organizationId: 'GOV004', timestamp: now, isRead: false, dataSourceType: 'DEMO' }
];

export const demoComplaints: Complaint[] = [
  { complaintId: 'CMP-001', organizationId: 'NGO003', category: 'FACILITY', description: 'Lack of proper medical doctor and expired medicines at Navjeevan Rehab Centre.', status: 'ACTION_REQUIRED', priority: 'CRITICAL', submittedAt: '2024-01-14T10:30:00Z', dataSourceType: 'DEMO' },
  { complaintId: 'CMP-002', organizationId: 'NGO010', category: 'FINANCIAL', description: 'Beneficiary stipend withholding and delayed DBT transfers reported by SC youth batch.', status: 'UNDER_INVESTIGATION', priority: 'HIGH', submittedAt: '2024-02-18T14:15:00Z', dataSourceType: 'DEMO' },
  { complaintId: 'CMP-003', organizationId: 'GOV004', category: 'EQUIPMENT', description: 'Delay in delivery of mechanized sanitation safety suits under NAMASTE scheme.', status: 'ACKNOWLEDGED', priority: 'MEDIUM', submittedAt: '2024-03-02T11:00:00Z', dataSourceType: 'DEMO' },
  { complaintId: 'CMP-004', organizationId: 'NGO008', category: 'DOCUMENTATION', description: 'Discrepancy in beneficiary enrollment register during flood relief distribution.', status: 'UNDER_INVESTIGATION', priority: 'HIGH', submittedAt: '2024-03-10T16:20:00Z', dataSourceType: 'DEMO' },
  { complaintId: 'CMP-005', organizationId: 'NGO005', category: 'FACILITY', description: 'Learning center emergency exit obstructed by storage cartons in Mumbai center.', status: 'RESOLVED', priority: 'MEDIUM', submittedAt: '2024-03-20T09:45:00Z', dataSourceType: 'DEMO' },
  { complaintId: 'CMP-006', organizationId: 'NGO004', category: 'HEALTHCARE', description: 'Request for additional monthly visits by Mobile Healthcare Unit for rural senior citizens.', status: 'OPEN', priority: 'LOW', submittedAt: '2024-04-01T12:00:00Z', dataSourceType: 'DEMO' },
  { complaintId: 'CMP-007', organizationId: 'GOV001', category: 'INFRASTRUCTURE', description: 'Tactile directional guide flooring damaged near Library corridor entrance.', status: 'RESOLVED', priority: 'LOW', submittedAt: '2024-02-20T10:00:00Z', dataSourceType: 'DEMO' },
  { complaintId: 'CMP-008', organizationId: 'NGO001', category: 'APPRECIATION', description: 'Commendation from local government school for punctual, hygienic mid-day meal delivery.', status: 'CLOSED', priority: 'INFO', submittedAt: '2024-03-15T08:30:00Z', dataSourceType: 'DEMO' }
];

export const demoCCTV = [
  { id: 'CAM-001', organizationId: 'GOV001', name: 'Demo Institution Entrance', location: 'Entrance', status: 'ONLINE', streamType: 'SIMULATED', dataSourceType: 'DEMO', verificationStatus: 'DEMO', streamUrl: '/cctv/cam1.jpg', resolution: '1080p', isAnomalous: false },
  { id: 'CAM-002', organizationId: 'GOV001', name: 'Demo Institution Corridor', location: 'Corridor A', status: 'ONLINE', streamType: 'SIMULATED', dataSourceType: 'DEMO', verificationStatus: 'DEMO', streamUrl: '/cctv/cam2.jpg', resolution: '1080p', isAnomalous: false },
  { id: 'CAM-003', organizationId: 'NGO003', name: 'Demo NGO Office', location: 'Reception', status: 'ONLINE', streamType: 'SIMULATED', dataSourceType: 'DEMO', verificationStatus: 'DEMO', streamUrl: '/cctv/cam3.jpg', resolution: '1080p', isAnomalous: false },
  { id: 'CAM-004', organizationId: 'NGO004', name: 'Demo Project Facility', location: 'Parking Lot', status: 'WARNING', streamType: 'SIMULATED', dataSourceType: 'DEMO', verificationStatus: 'DEMO', streamUrl: '/cctv/cam4.jpg', resolution: '720p', isAnomalous: true },
  { id: 'CAM-005', organizationId: 'GOV003', name: 'Demo Reception Area', location: 'Reception', status: 'ONLINE', streamType: 'SIMULATED', dataSourceType: 'DEMO', verificationStatus: 'DEMO', streamUrl: '/cctv/cam5.jpg', resolution: '1080p', isAnomalous: false },
  { id: 'CAM-006', organizationId: 'GOV004', name: 'Demo Campus Entrance', location: 'Main Gate', status: 'ONLINE', streamType: 'SIMULATED', dataSourceType: 'DEMO', verificationStatus: 'DEMO', streamUrl: '/cctv/cam6.jpg', resolution: '1080p', isAnomalous: false },
  { id: 'CAM-007', organizationId: 'NGO001', name: 'Demo Activity Room', location: 'Classroom 1', status: 'ONLINE', streamType: 'SIMULATED', dataSourceType: 'DEMO', verificationStatus: 'DEMO', streamUrl: '/cctv/cam7.jpg', resolution: '1080p', isAnomalous: false },
  { id: 'CAM-008', organizationId: 'GOV002', name: 'Demo Building Exterior', location: 'Perimeter Wall', status: 'OFFLINE', streamType: 'SIMULATED', dataSourceType: 'DEMO', verificationStatus: 'DEMO', streamUrl: '/cctv/cam8.jpg', resolution: '4K', isAnomalous: true, lastPingAt: new Date(Date.now() - 36000000).toISOString() },
];

export const demoFindings = [
  { id: 'FND-401', inspectionId: 'INSP-2024-004', organizationId: 'NGO003', title: 'Resident Medical Doctor Absent for 3 Consecutive Days', severity: 'CRITICAL', category: 'Staffing', description: 'Mandatory on-site RMP doctor was missing from rehabilitation clinic during surprise vigilance check, violating NAPDDR operating guidelines.', actionRequired: 'Immediate deployment of registered medical practitioner with MBBS credentials and biometric attendance.', status: 'OPEN', reportedDate: '2024-01-18' },
  { id: 'FND-402', inspectionId: 'INSP-2024-004', organizationId: 'NGO003', title: 'Expired Psychotropic Medication in Dispensary Stock', severity: 'CRITICAL', category: 'Safety', description: 'Batch #MD-8821 expired 4 months prior was found stored alongside active patient prescriptions in the de-addiction recovery ward.', actionRequired: 'Confiscate expired stock and produce verified pharmacy disposal certificate signed by CMO.', status: 'OPEN', reportedDate: '2024-01-18' },
  { id: 'FND-1001', inspectionId: 'INSP-2024-010', organizationId: 'NGO010', title: 'Stipend Disbursement Bank Reconciliations Missing for Q1', severity: 'HIGH', category: 'Finance', description: 'Beneficiary payment vouchers not matched with bank account statements for 48 vocational students under PM-DAKSH course.', actionRequired: 'Submit audited bank reconciliation statement with Aadhaar DBT confirmation.', status: 'OPEN', reportedDate: '2024-04-20' },
  { id: 'FND-701', inspectionId: 'INSP-2024-007', organizationId: 'NGO005', title: 'Emergency Fire Exit Corridor Obstructed with Cartons', severity: 'HIGH', category: 'Safety', description: 'Secondary egress corridor in educational learning center piled with packaging cartons, violating National Building Code Part 4.', actionRequired: 'Clear corridor immediately and guarantee 1.8m clear passageway.', status: 'RESOLVED', reportedDate: '2024-03-24' },
  { id: 'FND-1401', inspectionId: 'INSP-2024-014', organizationId: 'NGO008', title: 'Beneficiary Contact Details Non-Verifiable in 24 Records', severity: 'HIGH', category: 'Beneficiaries', description: 'Sample telephone audit revealed disconnected numbers for 24 listed skill course beneficiaries in flood relief restoration project.', actionRequired: 'Conduct physical door-to-door verification and update live GIS coordinates.', status: 'OPEN', reportedDate: '2024-02-02' },
  { id: 'FND-301', inspectionId: 'INSP-2024-003', organizationId: 'GOV004', title: 'Delay in Digitization of Physical Loan Agreements', severity: 'MEDIUM', category: 'Records', actionRequired: 'Digitize pending 28 physical loan agreements into Smart Inspect cloud repository.', status: 'IN_PROGRESS', reportedDate: '2024-04-10' },
  { id: 'FND-302', inspectionId: 'INSP-2024-003', organizationId: 'GOV004', title: 'Safety Harness Buffer Inventory Below Safe Threshold', severity: 'MEDIUM', category: 'Safety', description: 'Stock of CE-marked dual lanyard safety harnesses for mechanised sewer cleaners insufficient for next quarter.', actionRequired: 'Procure minimum 50 CE-marked dual-lanyard safety harnesses for sanitation workers under NAMASTE.', status: 'OPEN', reportedDate: '2024-04-10' },
  { id: 'FND-2101', inspectionId: 'INSP-2024-021', organizationId: 'GOV010', title: 'District Verification Reports Pending from 4 Regional Centers', severity: 'MEDIUM', category: 'Records', description: 'Field reports on manual scavenger alternative rehabilitation delayed from 4 district nodal offices.', actionRequired: 'Issue formal compliance directive to regional nodal officers.', status: 'IN_PROGRESS', reportedDate: '2024-03-26' },
  { id: 'FND-101', inspectionId: 'INSP-2024-001', organizationId: 'GOV001', title: 'Tactile Directional Pathway Worn Near Library Corridor', severity: 'LOW', category: 'Infrastructure', description: 'Polyurethane tactile warning floor studs for visually impaired trainees damaged near Corridor B entrance.', actionRequired: 'Replace polyurethane tactile floor warning studs in Corridor B in compliance with Accessible India guidelines.', status: 'RESOLVED', reportedDate: '2024-02-25' },
  { id: 'FND-501', inspectionId: 'INSP-2024-005', organizationId: 'NGO002', title: 'First Aid Emergency Kit Consumables Exhausted in Room 4', severity: 'LOW', category: 'Safety', description: 'First aid kit in youth skill workshop depleted of burn ointment and sterile gauze.', actionRequired: 'Restock antiseptic ointments and sterile bandages.', status: 'RESOLVED', reportedDate: '2024-04-05' },
  { id: 'FND-1101', inspectionId: 'INSP-2024-011', organizationId: 'GOV002', title: 'Biometric Attendance Server UPS Battery Due for Servicing', severity: 'LOW', category: 'Infrastructure', description: 'Backup battery runtime dropped below 30 minutes for central Aadhaar authentication kiosk.', actionRequired: 'Complete scheduled OEM preventative maintenance.', status: 'RESOLVED', reportedDate: '2024-02-05' },
  { id: 'FND-201', inspectionId: 'INSP-2024-002', organizationId: 'NGO001', title: 'Ramp Slope Gradient Violation (1:8 instead of 1:12)', severity: 'HIGH', category: 'Infrastructure', description: 'External wheelchair ramp at facility entrance exceeds maximum allowable gradient mandated by RPwD Act 2016.', actionRequired: 'Re-engineer ramp with maximum 1:12 slope and install continuous dual handrails.', status: 'OPEN', reportedDate: '2024-03-12' },
  { id: 'FND-601', inspectionId: 'INSP-2024-006', organizationId: 'NGO004', title: 'Resident Emergency Call Bell Cord Detached in Bed 12', severity: 'LOW', category: 'Safety', description: 'Elderly bedridden resident room emergency nurse notification wire was unplugged.', actionRequired: 'Re-solder call bell trigger and perform daily nursing shift verification test.', status: 'RESOLVED', reportedDate: '2024-02-20' },
  { id: 'FND-1201', inspectionId: 'INSP-2024-012', organizationId: 'NGO009', title: 'Quarterly Water Potability Laboratory Certificate Overdue', severity: 'MEDIUM', category: 'Safety', description: 'Mandatory bacteriological water testing report for hostel drinking water supply expired 35 days ago.', actionRequired: 'Obtain NABL accredited laboratory water potability certificate within 15 days.', status: 'IN_PROGRESS', reportedDate: '2024-02-28' },
  { id: 'FND-1501', inspectionId: 'INSP-2024-015', organizationId: 'NGO006', title: 'Non-Functional Fire Hydrant Valve in North Wing', severity: 'CRITICAL', category: 'Safety', description: 'Main wet-riser fire hydrant nozzle seized due to corrosion in child residential dormitory block.', actionRequired: 'Replace brass hydrant landing valve immediately and submit firefighting system pressure test certificate.', status: 'OPEN', reportedDate: '2024-03-08' }
];
