import { useState } from 'react';
import { Database, AlertTriangle, ShieldCheck, CheckCircle2, Info } from 'lucide-react';
import { seedDemoData, removeDemoData } from '../services/demoSeeder';

export default function Settings() {
  const [showConfirmModal, setShowConfirmModal] = useState(false);
  const [statusMsg, setStatusMsg] = useState<{ type: 'success' | 'error', text: string } | null>(null);
  
  // Hardcoded for prototype demonstration
  const isSuperAdmin = true; 

  const handleSeed = () => {
    const result = seedDemoData();
    setStatusMsg({ type: result.success ? 'success' : 'error', text: result.message });
    setTimeout(() => setStatusMsg(null), 4000);
  };

  const handleRemove = () => {
    const result = removeDemoData();
    setStatusMsg({ type: result.success ? 'success' : 'error', text: result.message });
    setShowConfirmModal(false);
    setTimeout(() => setStatusMsg(null), 4000);
  };

  return (
    <div className="max-w-4xl space-y-6">
      <div>
        <h1 className="text-2xl font-bold text-slate-800">System Settings</h1>
        <p className="text-slate-600 mt-1">Manage system configurations and data.</p>
      </div>

      {statusMsg && (
        <div className={`p-4 rounded-lg flex items-center gap-3 ${
          statusMsg.type === 'success' ? 'bg-green-50 text-green-700 border border-green-200' : 'bg-red-50 text-red-700 border border-red-200'
        }`}>
          {statusMsg.type === 'success' ? <CheckCircle2 className="w-5 h-5" /> : <AlertTriangle className="w-5 h-5" />}
          <span className="font-medium">{statusMsg.text}</span>
        </div>
      )}

      {/* Demo Data Management Panel */}
      {isSuperAdmin && (
        <div className="bg-white rounded-xl border border-slate-200 shadow-sm overflow-hidden">
          <div className="p-4 border-b border-slate-200 bg-slate-50 flex items-center gap-3">
            <div className="w-10 h-10 rounded-full bg-indigo-100 flex items-center justify-center">
              <Database className="w-5 h-5 text-indigo-600" />
            </div>
            <div>
              <h2 className="font-bold text-slate-800">Demo Data Management</h2>
              <p className="text-sm text-slate-500">SUPER_ADMIN Only Feature</p>
            </div>
          </div>
          
          <div className="p-6 space-y-6">
            <div className="flex items-start gap-4 p-4 bg-blue-50 border border-blue-100 rounded-lg">
              <Info className="w-5 h-5 text-blue-600 shrink-0 mt-0.5" />
              <div>
                <h3 className="font-bold text-blue-900">About Demo Data</h3>
                <p className="text-sm text-blue-800 mt-1">
                  Seeding data inserts completely fictional organizations and projects strictly for UI demonstration. 
                  These records are visually tagged with <strong>DEMO DATA</strong>. Removing demo data will ONLY delete records explicitly tagged as demo.
                </p>
              </div>
            </div>

            <div className="flex flex-col sm:flex-row gap-4">
              <button 
                onClick={handleSeed}
                className="flex-1 btn-primary py-3 flex items-center justify-center gap-2"
              >
                <Database className="w-4 h-4" />
                Seed Demo Organizations
              </button>
              
              <button 
                onClick={() => setShowConfirmModal(true)}
                className="flex-1 bg-white border-2 border-red-200 text-red-600 hover:bg-red-50 py-3 rounded-lg font-bold flex items-center justify-center gap-2 transition-colors"
              >
                <AlertTriangle className="w-4 h-4" />
                Remove Demo Data
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Removal Confirmation Modal */}
      {showConfirmModal && (
        <div className="fixed inset-0 bg-slate-900/50 backdrop-blur-sm z-50 flex items-center justify-center p-4">
          <div className="bg-white rounded-xl shadow-xl max-w-md w-full overflow-hidden animate-in fade-in zoom-in-95 duration-200">
            <div className="p-6 text-center">
              <div className="w-16 h-16 bg-red-100 rounded-full flex items-center justify-center mx-auto mb-4">
                <AlertTriangle className="w-8 h-8 text-red-600" />
              </div>
              <h2 className="text-xl font-bold text-slate-800 mb-2">Remove Demo Data?</h2>
              <p className="text-slate-600 text-sm mb-6">
                This action will delete all fictional organizations and projects generated by the seeder (tagged with <code className="bg-slate-100 px-1 py-0.5 rounded text-xs">isDemo: true</code>).
                <br/><br/>
                Are you absolutely sure you want to proceed?
              </p>
              
              <div className="flex gap-3">
                <button 
                  onClick={() => setShowConfirmModal(false)}
                  className="flex-1 btn-secondary py-2"
                >
                  Cancel
                </button>
                <button 
                  onClick={handleRemove}
                  className="flex-1 bg-red-600 hover:bg-red-700 text-white font-bold rounded-lg py-2 transition-colors flex items-center justify-center gap-2"
                >
                  <ShieldCheck className="w-4 h-4" />
                  Yes, Remove
                </button>
              </div>
            </div>
          </div>
        </div>
      )}

    </div>
  );
}
